spring:
  datasource:
    username: postgres
    password: adminPassword
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      leak-detection-threshold: 60000
      maximum-pool-size: 2
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        default_schema: movies
        jdbc.lob.non_contextual_creation: true
        hibernate.order_inserts: true
        hibernate.order_updates: true
        hibernate.jdbc.batch_size: 10
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
logging:
  level:
    root: info
    org.springframework: info
